export default {
    SET_ACTIVE_PORTFOLIO: "SET_ACTIVE_PORTFOLIO",
    SET_CURRENCIES_LOADING: "SET_CURRENCIES_LOADING",
    SET_CURRENCIES: "SET_CURRENCIES",
    SET_USER_AUTH_LOADING: "SET_USER_AUTH_LOADING",
    SET_USER_AUTH_DATA: "SET_USER_AUTH_DATA",
    SET_USER_LOADING: "SET_USER_LOADING",
    SET_USER_DATA: "SET_USER_DATA",
    SET_PORTFOLIO_DATA: "SET_PORTFOLIO_DATA",
};
