source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
# Use sqlite3 as the database for Active Record
gem 'pg', '~> 1.2', '>= 1.2.2'
# Use Puma as the app server
gem "puma", ">= 4.3.3"

# Build CMC API wrapper
gem 'coinmarketcap'

# Build JSON APIs
gem 'active_model_serializers', '~> 0.10.10'

# Use Redis adapter to run Action Cable/sidekiq in production
gem 'redis', '~> 4.0'
gem 'sidekiq', '~> 6.0', '>= 6.0.5'

# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'jwt', '~> 2.2', '>= 2.2.1'

# Service Objects pattern
gem 'interactor', '~> 3.1', '>= 3.1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.4', '>= 1.4.6'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 1.1', '>= 1.1.1'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'ruby-debug-ide'
  gem 'debase'
end

group :test do
  gem 'simplecov', require: false
end

group :development, :test do
  gem 'rspec-rails', '~> 4.0.0.beta4'
  gem 'rswag'
  gem 'rails-controller-testing'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'factory_bot_rails', '~> 5.1', '>= 5.1.1'
  gem 'faker'
  gem 'database_cleaner'
end


