export default {
    SET_APP_LOADING: "SET_APP_LOADING",
    SET_ACTIVE_PORTFOLIO: "SET_ACTIVE_PORTFOLIO",
    SET_CURRENCIES_LOADING: "SET_CURRENCIES_LOADING",
    SET_CURRENCIES: "SET_CURRENCIES",
    SET_USER_AUTH_LOADING: "SET_USER_AUTH_LOADING",
    SET_USER_AUTH_DATA: "SET_USER_AUTH_DATA",
    SET_USER_LOADING: "SET_USER_LOADING",
    SET_USER_DATA: "SET_USER_DATA",
    SET_PORTFOLIO_DATA: "SET_PORTFOLIO_DATA",
    ADD_PORTFOLIO_DATA: "ADD_PORTFOLIO_DATA",
    SET_PORTFOLIO_LOADING: "SET_PORTFOLIO_LOADING",
    SET_PORTFOLIO_ITEM_NAME: "SET_PORTFOLIO_ITEM_NAME",
};
